#!/bin/bash

#exit on first error
set -e

export BUILD_PWD=`pwd`

export CYANOGEN_BASE_PATH=$BUILD_PWD/cm-12.0
export CYANOGEN_PRODUCT_PATH=$CYANOGEN_BASE_PATH/out/target/product/archos_g9

export DESTINATION_PATH=$BUILD_PWD/archos_image


echo "Build PWD: $BUILD_PWD"

function callRepo
{
   shift
   echo "Calling repo command in repository: $CYANOGEN_BASE_PATH with params: $*"
   cd $CYANOGEN_BASE_PATH
   repo $*
   cd $BUILD_PWD
}

function inject
{
  echo "Injecting propritary files for archos device..."
  cp -rpv $BUILD_PWD/android_injection/* $CYANOGEN_BASE_PATH/
}

function buildImage
{
echo "Checking ext4 image..."
fsck.ext4 -p $DESTINATION_PATH/archos.ext4.update

echo "Mounting base image..."
sudo mount $DESTINATION_PATH/archos.ext4.update $DESTINATION_PATH/mount/

echo "Clear image..."
sudo rm -rf $DESTINATION_PATH/mount/*

echo "Extracting base image"
sudo tar xfj archos_base_image.tar.bz2 -C $DESTINATION_PATH/mount/

# Base image has an tmp folder. I'm too lazy to change the image and upload a new one...so modify does also the trick.
if [ -e $DESTINATION_PATH/mount/tmp ];
then
  sudo rm -rf $DESTINATION_PATH/mount/tmp
fi

echo "Copy root folder from cyanogen mod..."
sudo cp -rf $CYANOGEN_PRODUCT_PATH/root/* $DESTINATION_PATH/mount/

echo "Copy system folder from cyanogen mod..."
sudo cp -rf $CYANOGEN_PRODUCT_PATH/system $DESTINATION_PATH/mount/

echo "Copy gapps package..."
sudo cp -rf $DESTINATION_PATH/gapps/system $DESTINATION_PATH/mount/

echo "Copy init.rc and ueventd.rc ..."
sudo cp $CYANOGEN_BASE_PATH/device/archos/archos_g9/prebuilt/root/ueventd.rc $DESTINATION_PATH/mount/ueventd.rc

sudo chmod 0755 $DESTINATION_PATH/mount/system/vendor/bin/*

echo "Set permissions for su"
echo "Avoiding the suid bit - this doesn't work on Android 4.3..."
sudo chown 0:0 $DESTINATION_PATH/mount/system/xbin/su
sudo chmod 06755 $DESTINATION_PATH/mount/system/bin/su
sudo chown 0:0 $DESTINATION_PATH/mount/system/bin/su
sudo chmod 0755 $DESTINATION_PATH/mount/system/bin/su

echo "Removing sgx544 libraries"
sudo find $DESTINATION_PATH/mount/system/vendor/lib/ -name "*544*" -exec rm {} +

echo "Correcting permission for initd and compcache binaries"
#sudo chmod 0755 $DESTINATION_PATH/mount/system/bin/handle_compcache
#sudo chmod 0755 $DESTINATION_PATH/mount/system/bin/compcache
sudo chmod 0755 $DESTINATION_PATH/mount/system/bin/sysinit

echo "Correcting permissions for system/framework files"
sudo chmod 0644 $DESTINATION_PATH/mount/system/framework/*

echo "Unmounting base image..."
sudo umount $DESTINATION_PATH/mount

echo "Archos image is at the following position:"
echo "$DESTINATION_PATH/archos.ext4.update"
echo "If you want to mount it use:"
echo "sudo mount $DESTINATION_PATH/archos.ext4.update $DESTINATION_PATH/mount/"
echo "If you want to transfer it to archos device use:"
echo "adb push $DESTINATION_PATH/archos.ext4.update /data/media/ && adb reboot"
}

function makeProject
{
export USE_LINARO_COMPILER_FLAGS=yes
export ANDROID_EABI_TOOLCHAIN_DIR=linaro-4.8
export ARM_EABI_TOOLCHAIN_DIR=linaro-4.8

    echo "$CYANOGEN_BASE_PATH: Rebuilding bionic headers, based from external/kernel-headers package"
    cd $CYANOGEN_BASE_PATH

    if [ $1 != "nobionic" ]; then
	echo "Update bionic kernel headers..."
	./bionic/libc/kernel/tools/update_all.py
    fi

    inject

    if [ $1 == "clean" ]; then
	echo "Cleaning target output folder..."
	rm -rf out/target
    fi

    echo "Now building the project..."
    #. build/envsetup.sh && lunch cm_archos_g9-userdebug && mka update-api && mka ${@:2}
    #. build/envsetup.sh && lunch cm_archos_g9-userdebug && mka showcommands ${@:2}
    . build/envsetup.sh && lunch cm_archos_g9-userdebug && mka ${@:2}
    cd $BUILD_PWD
}

function cleanGitRepos
{
    callRepo repo forall -c git reset --hard
    callRepo repo forall -c git clean -fd
    $CYANOGEN_BASE_PATH/vendor/cm/get-prebuilts
}

function prepareLinaroToolChain
{
    TAR_FILE=android-toolchain-eabi-4.8-2014.01-x86.tar.bz2
    cd $CYANOGEN_BASE_PATH
    wget -c http://releases.linaro.org/14.01/components/android/toolchain/4.8/$TAR_FILE
    cd $CYANOGEN_BASE_PATH/prebuilts/gcc/linux-x86/arm
    tar -xvjf ../../../../$TAR_FILE
    if [ -e linaro-4.8 ]; then
	rm -rf linaro-4.8
    fi
    mv android-toolchain-eabi linaro-4.8
}

function applyCherryPicks
{
    set +e
    echo "Performing cherry-picks..."

     # build: allow usage of oracle jdk on linux
     #cd $CYANOGEN_BASE_PATH/build
     #git fetch http://review.cyanogenmod.org/CyanogenMod/android_build refs/changes/94/79494/1 && git checkout FETCH_HEAD

     # Apply: Fix "FIONREAD not done before read" error 
     #cd $CYANOGEN_BASE_PATH/external/bluetooth/bluedroid
     #git remote remove Quallenauge_bluedroid; git remote add Quallenauge_bluedroid https://github.com/Quallenauge/android_external_bluetooth_bluedroid.git && git fetch Quallenauge_bluedroid && \
     #git cherry-pick 1fd6d85d2bbcbbfbc6f50b92f6a5c06d32243c8a
     

     set -e
     # Add ti specific hwcomposer 1.1
     cd $CYANOGEN_BASE_PATH/frameworks/native
     git remote remove Quallenauge_frameworks_native; git remote add Quallenauge_frameworks_native https://github.com/Quallenauge/android_frameworks_native.git && git fetch Quallenauge_frameworks_native && \
     git cherry-pick c6bff791550a938dffa2815e6ad7ca8aa99d2834

     # Support forcing all screenshots into a CPU consumer
     #cd $CYANOGEN_BASE_PATH/frameworks/native
     #git fetch http://review.cyanogenmod.org/CyanogenMod/android_frameworks_native refs/changes/41/79441/1 && git cherry-pick FETCH_HEAD

     # Re-Enable non-PIE executables support
     cd $CYANOGEN_BASE_PATH/bionic
     #git revert --no-edit 76e289c026f11126fc88841b3019fd5bb419bb67
     git fetch http://review.cyanogenmod.org/CyanogenMod/android_bionic refs/changes/36/79136/2 && git cherry-pick FETCH_HEAD

     # Disable pmf=1
     #cd $CYANOGEN_BASE_PATH/external/wpa_supplicant_8    
     #git revert --no-edit faa2d7a546126325077cabf13811078749faa6cd

     # fix outgoing calls on LP
     cd $CYANOGEN_BASE_PATH/hardware/ril
     git fetch http://review.cyanogenmod.org/CyanogenMod/android_hardware_ril refs/changes/64/82164/1 && git cherry-pick FETCH_HEAD

     # Re-Enable domx calls
     #cd $CYANOGEN_BASE_PATH/frameworks/native
     #git remote remove MWisBest_frameworks_av; git remote add MWisBest_frameworks_native https://github.com/MWisBest/android_frameworks_av.git && git fetch MWisBest_frameworks_av && \
     #git cherry-pick 67be76171d588aebaa8227614a5669c29af937d5 &&
     #git cherry-pick da0be12c8dfb71c751982e14f0dd38093f7e92ef &&
     #git cherry-pick 788b119f78102d3da785b3c234713d60443b642d

     # Android: driver_nl80211: implement NoA/p2p_ps/set_wps_ie stubs
     #cd $CYANOGEN_BASE_PATH/hardware/ti/wlan
     #git fetch http://review.cyanogenmod.org/CyanogenMod/android_hardware_ti_wlan refs/changes/20/78120/1 && git cherry-pick FETCH_HEAD

     # capabilities ERANG error fix
     cd $CYANOGEN_BASE_PATH/external/wpa_supplicant_8
     git fetch http://review.cyanogenmod.org/CyanogenMod/android_external_wpa_supplicant_8 refs/changes/53/78853/1 && git cherry-pick FETCH_HEAD

     # nl80211: update includes to L bionic and add unhandled attributes to nl80211
     #cd $CYANOGEN_BASE_PATH/hardware/ti/wlan
     #git fetch http://review.cyanogenmod.org/CyanogenMod/android_hardware_ti_wlan refs/changes/60/80360/1 && git cherry-pick FETCH_HEAD

}

case "$1" in
"repo")
	callRepo $*
;;
"buildImage")
	buildImage
;;
"make")
	makeProject dummyArg ${@:2}
;;
"makeLight")
	makeProject nobionic ${@:2}
;;

"makeFull")
	makeProject clean ${@:2}
;;
"reset")
	cleanGitRepos
;;
"inject")
	inject
;;
"prepareLinaro")
	prepareLinaroToolChain
;;
"sync")
  echo "Perform an inject to ensure that changes are not overwritten..."
  if [ $# -eq 1 ];then
    echo "Injecting data"
    inject
  fi

  dateStr=`date +"%d_%m_%Y-%H_%M_%S"`
  LAST_REV_FILE=$BUILD_PWD/lastRevs.txt
  cd $CYANOGEN_BASE_PATH
  if [ -e $LAST_REV_FILE ]; then
    echo "Last sync wasn't successful...using last revisions"
  else
    echo "Creating new revision file"
    repo forall -c 'echo "`pwd`|`git rev-parse HEAD`"' >$LAST_REV_FILE
  fi
  echo "Updating repo...."
#  cd $CYANOGEN_PRODUCT_PATH
  cd $CYANOGEN_BASE_PATH
  repo sync
  if [ 0 == $? ]; then
    echo "Apply cherry picks..."
    applyCherryPicks  

    echo "Sync was successful...creating changelog now"
    OUT_FILE=$BUILD_PWD/Changes_$dateStr.txt
    set -e

    echo "" >$OUT_FILE

    while read line; do
      #echo "$line"
      FOLDER=`echo $line | cut -d'|' -f1`
      HASH=`echo $line | cut -d'|' -f2`

      #echo "Folder=$FOLDER"
      #echo "Hash=$HASH"
      if [ ! -d $FOLDER ]; then
          continue;
      fi
      cd $FOLDER      
      echo "Checking $FOLDER"
#     if [ `git rev-list --max-count=2 --all | wc -l` -eq 1 ]; then
#       echo "Skipping repo, because only one commit available"
#       continue
#     fi
      NEW_HASH=`git rev-parse HEAD`
      if [ "$NEW_HASH" != "$HASH" ]; then
        echo "Folder $FOLDER has changed... $NEW_HASH != $HASH"
        echo "-----------------------------------------------------------------" >>$OUT_FILE
        echo "$FOLDER $HASH..$NEW_HASH" >>$OUT_FILE
        set +e
        git log $HASH..$NEW_HASH >>$OUT_FILE
        set -e
        #git log $NEW_HASH..$HASH >>$OUT_FILE
      fi
    done < $LAST_REV_FILE
  fi
  echo "Backup last revision file..."
  mv $LAST_REV_FILE "$LAST_REV_FILE"_"$dateStr"
  cd $BUILD_PWD
;;
"release")
	makeProject dummyArg ${@:2} 2>&1 | tee build.log
	echo -n "Waiting for user.... press RETURN to continue..." && read
	buildImage
	dateStr=`date +"%d_%m_%Y-%H_%M_%S"`
	RELEASE_DIR_PATH=$BUILD_PWD/releases/$dateStr
	mkdir $RELEASE_DIR_PATH
	mkdir $RELEASE_DIR_PATH/revisions

	cp $DESTINATION_PATH/archos.ext4.update $RELEASE_DIR_PATH/
	cp $CYANOGEN_PRODUCT_PATH/kernel $RELEASE_DIR_PATH/zImage
	cp initramfs.cpio.lzo $RELEASE_DIR_PATH/initramfs.cpio.lzo

	git rev-parse HEAD >$RELEASE_DIR_PATH/revisions/rev_buildRepo.txt
	callRepo repo manifest -o "$RELEASE_DIR_PATH/revisions/manifest.xml" -r
	cd android_injection
	git rev-parse HEAD >$RELEASE_DIR_PATH/revisions/rev_android_injection.txt
	
	cd $CYANOGEN_BASE_PATH
	LAST_REV_FILE=$RELEASE_DIR_PATH/revisions/lastRevs.txt
	echo "Creating revision file from current state for release..."
	repo forall -c 'echo "`pwd`|`git rev-parse HEAD`"' >$LAST_REV_FILE
;;
"cherryPicks")
	applyCherryPicks
;;
*)
	echo "Command $1 not supported"
;;
esac
